version = 0.1
[default.deploy.parameters]
stack_name = "go-serverless"
resolve_s3 = true
s3_prefix = "go-serverless"
region = "us-east-1"
profile = "hikkaigo"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []
